<?php
$planMsg = $this->planNotice();
?>
<script>
    require(['jquery', 'domReady!'], function ($) {
        let carrierDiv = '#WweLtConnSettings_first-head';
        WweLtCurrentPlanNote($, '<?php echo $planMsg; ?>', carrierDiv);
    });
</script>
<div class="pp-buttons-container">
    <button class="primary" id="<?php echo $block->getId() ?>" connAjaxUrl="<?php echo $block->getAjaxCheckUrl() ?>">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>

<!-- Display Responses Messages -->
<div id="WweLt-con-msg" style="display: none; margin-top: 20px; padding-right: 3px;"></div>
