<script>
    require([ 'jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            let carrierDiv = '#WweLtUserGuide_fourth-head';
            WweLtCurrentPlanNote($, '<?php echo $this->planNotice(); ?>', carrierDiv);
        });
    });
</script>
<div class="user-guide">
    <p>
        <?=
            /* @noEscape */ __(
                "The User Guide for this application is maintained on the publisher's website. To view it click <a href='%1' target='blank'>here</a> or paste the following link into your browser.",
                "https://eniture.com/magento2-worldwide-express-ltl-freight/#documentation"
            )
                                        ?>
    </p>
    <?= "https://eniture.com/magento2-worldwide-express-ltl-freight/#documentation" ?>
</div>
