<?php
$plan = $block->getCurrentPlan();
$advancedPlan = false;
$class = 'disabledDiv';
$disableInput = 'disabled="disabled"';
if ($plan == 3) {
    $advancedPlan = true;
    $class = '';
    $disableInput = '';
}
?>
<script>
    require(['jquery', 'domReady!'], function ($) {
        let carrierDiv = '#WweLtWarehouse_second-head';
        WweLtCurrentPlanNote($, '<?php echo $block->planNotice(); ?>', carrierDiv);

        let canAddWh = <?php echo $block->addWhRestriction(); ?>;
        WweLtAddWarehouseRestriction(canAddWh);
    });
    const WweLtAjaxUrl = '<?=  $block->getAjaxUrl() ?>';
    const WweLtAdvancePlan = '<?=  $advancedPlan ?>';
</script>
</form>
<div class="main-container">
    <h1>
        <?= /* @noEscape */
        __('Warehouses') ?>
    </h1>
    <a href="#" id="WweLt-add-wh-btn" class="add-wh-btn hide-val en-btn" title="<?= /* @noEscape */
    __('Add Warehouse') ?>">
        <?= /* @noEscape */
        __('Add') ?>
    </a>
    <div class="wh-text">
        <p>
            <?= __('Warehouses that inventory all products not otherwise identified as drop shipped items. The warehouse with the lowest shipping cost to the destination is used for quoting purposes.') ?>
        </p>
    </div>
    <div id="WweLt-wh-msg"></div>

    <table class="warehouse" id="append-warehouse">
        <thead>
        <tr>
            <th>
                <?= __('City') ?>
            </th>
            <th>
                <?= __('State') ?>
            </th>
            <th>
                <?= __('Zip') ?>
            </th>
            <th>
                <?= __('Country') ?>
            </th>
            <th>
                <?= __('Action') ?>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        $getWarehouses = $block->dataHelper->fetchWarehouseSecData('warehouse');
        if ($getWarehouses) {
            foreach ($getWarehouses as $r) {
                ?>
                <tr id="row_<?= $r['warehouse_id']; ?>" data-id="<?= $r['warehouse_id']; ?>">
                    <td>
                        <?= $r['city']; ?>
                    </td>
                    <td>
                        <?= $r['state']; ?>
                    </td>
                    <td>
                        <?= $r['zip']; ?>
                    </td>
                    <td>
                        <?= $r['country']; ?>
                    </td>
                    <td>
                        <a href="javascript:;" data-id="<?= $r['warehouse_id']; ?>" title="<?= __('Edit') ?>"
                           class="WweLt-edit-wh">
                            <?= __('Edit') ?>
                        </a> |
                        <a href="javascript:;" data-id="<?= $r['warehouse_id']; ?>" title="<?= __('Delete') ?>"
                           class="WweLt-del-wh">
                            <?= __('Delete') ?>
                        </a>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>

    <hr class="wh-hr">
</div>
<!--     Add Popup for new warehouse-->
<div id="WweLt-wh-modal" class="add-wh-popup">
    <form method="post" id="WweLt-wh-form" enctype="multipart/form-data" autocomplete="off"
          data-mage-init='{"validation":{}}'>


        <div id="WweLt-wh-modal-msg"></div>
        <input type="hidden" name="location" value="warehouse">
        <input type="hidden" name="originId" id="edit-form-id">
        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= __('Zip') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alphanum" title="<?= __('Zip') ?>" maxlength="6" name="zip"
                       placeholder="30214" id="WweLt-wh-zip">
            </div>
        </div>

        <div class="add-wh-input city-input">
            <div class="wh-input-label add-asterisk">
                <?= __('City') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required" title="<?= __('City') ?>" name="city" placeholder="Fayetteville"
                       id="wh-origin-city">
            </div>
        </div>

        <div class="add-wh-input city-select" style="display:none;">
            <div class="wh-input-label add-asterisk">
                <?= __('City') ?>
            </div>
            <div class="wh-input">
                <select id="actname"></select>
            </div>
        </div>

        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= __('State') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alpha" title="<?= __('State') ?>" maxlength="2" name="state"
                       placeholder="GA" id="wh-origin-state">
            </div>
        </div>

        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= __('Country') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alpha" title="<?= __('Country') ?>" maxlength="2"
                       name="country" placeholder="US" id="wh-origin-country">
            </div>
        </div>

        <!--In store Pickup Section-->
        <h3 class="wh-heading is-heading-left" id="wh-is-heading-left">
            <?= __('In-store Pick Up') ?>
        </h3>
        <?php if (!$advancedPlan): ?>
            <a class="is-heading-right" href="https://eniture.com/magento2-worldwide-express-ltl-freight">
                <?= __('Advanced Plan Required') ?>
            </a>
        <?php endif; ?>

        <div class="message message-error error wh-instore-miles-postal-err">
            <?= __('You must provide Miles or Postal Code.') ?>
        </div>

        <div id="disableddiv" class="<?= $class ?>">
            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Enable In-Store Pick Up') ?>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= __('Enable In-Store Pick Up') ?>" name="instore_enable"
                           id="enable-instore-pickup" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Offer if address is within (miles):') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Offer if address is within (miles)') ?>" class="digits"
                           maxlength="3" name="is_within_miles" id="within-miles" <?= $disableInput ?>
                           onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Offer if postal code matches:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Offer is postal code matches') ?>" name="is_postcode_match"
                           id="postcode-match"
                           data-role="<?= $advancedPlan ? 'tagsinput' : ''; ?>" <?= $disableInput ?> >
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Check Out Description:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Check Out Description') ?>" maxlength="25"
                           name="is_checkout_descp" placeholder="In-store pick up"
                           id="checkout-descp" <?= $disableInput ?>>
                </div>
            </div>
        </div>
        <!--In store Pickup Section End-->

        <!--Local Delivery Section-->

        <div class="row" style="clear: both">
            <h3 class="wh-heading ld-heading-left" id="wh-ld-heading-left">
                <?= __('Local Delivery') ?>
            </h3>
            <?php if (!$advancedPlan): ?>
                <a class="ld-heading-right" href="https://eniture.com/magento2-worldwide-express-ltl-freight">
                    <?= __('Advanced Plan Required') ?>
                </a>
            <?php endif; ?>
        </div>

        <div class="message message-error error wh-local-miles-postals-err">
            <?= __('You must provide Miles or Postal Code.') ?>
        </div>

        <!--Local Delivery Section Start-->
        <div id="disableddiv" class="<?= $class ?>">
            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Enable Local Delivery') ?>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= __('Enable Local Delivery') ?>" name="ld_enable"
                           id="enable-local-delivery" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Offer if address is within (miles):') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Offer if address is within (miles)') ?>" class="digits"
                           maxlength="3" name="ld_within_miles" value="" id="ld-within-miles" <?= $disableInput ?>
                           onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Offer if postal code matches:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Offer is postal code matches') ?>"
                           data-role="<?= $advancedPlan ? 'tagsinput' : ''; ?>" name="ld_postcode_match"
                           id="ld-postcode-match" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Check Out Description:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Check Out Description') ?>" maxlength="25"
                           name="ld_checkout_descp" placeholder="Local delivery"
                           id="ld-checkout-descp" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Local Delivery Fee') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Local Delivery Fee') ?>"
                           class="number validate-WweLt-positive-decimal-limit-2" maxlength="5" name="ld_fee"
                           id="ld-fee" <?= $disableInput ?> onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Suppress other rates') ?>
                    <div class="suppressTooltip">[ ? ]
                        <span
                            class="suppressTooltiptext"><?= __("This setting only suppresses rates that would otherwise be returned by the Eniture Technology products.") ?></span>
                    </div>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= __('Suppress other rates') ?>" name="ld_sup_rates"
                           id="ld-sup-rates" <?= $disableInput ?>>
                </div>
            </div>
        </div>
        <!--Local Delivery Section End-->
    </form>
</div>

