<?php
$plan = $block->getCurrentPlan();
$advancedPlan = false;
$class = 'disabledDiv';
$disableInput = 'disabled="disabled"';
if ($plan == 3) {
    $advancedPlan = true;
    $class = '';
    $disableInput = '';
}
?>
<script type="text/javascript">
    var WweLtDsAjaxUrl = '<?= $block->getDsAjaxUrl() ?>';
</script>
<div class="main-container">
    <h1>
        <?= __('Drop ships') ?>
    </h1>

    <a href="#add-ds-btn" class="en-btn" id="WweLt-add-ds-btn" title="<?= __('Add Drop Ship') ?>">
        <?= __('Add') ?>
    </a>
    <div class="wh-text ds">
        <p>
            <?= __("Locations that inventory specific items that are drop shipped to the destination. Use the product's settings page to identify it as a drop shipped item and its associated drop ship location. Orders that include drop shipped items will display a single figure for the shipping rate estimate that is equal to the sum of the cheapest option of each shipment required to fulfill the order.") ?>
        </p>
    </div>

    <div id="WweLt-ds-msg"></div>

    <table class="warehouse" id="append-dropship">
        <thead>
        <tr>
            <th>
                <?= __('Nickname') ?>
            </th>
            <th>
                <?= __('City') ?>
            </th>
            <th>
                <?= __('State') ?>
            </th>
            <th>
                <?= __('Zip') ?>
            </th>
            <th>
                <?= __('Country') ?>
            </th>
            <th>
                <?= __('Action') ?>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        $getDropships = $block->dataHelper->fetchWarehouseSecData('dropship');
        if ($getDropships) {
            foreach ($getDropships as $r) { ?>
                <tr id="row_<?= $r['warehouse_id']; ?>" data-id="<?= $r['warehouse_id']; ?>">
                    <td>
                        <?= $r['nickname']; ?>
                    </td>
                    <td>
                        <?= $r['city']; ?>
                    </td>
                    <td>
                        <?= $r['state']; ?>
                    </td>
                    <td>
                        <?= $r['zip']; ?>
                    </td>
                    <td>
                        <?= $r['country']; ?>
                    </td>
                    <td>
                        <a href="javascript:;" data-id="<?= $r['warehouse_id']; ?>" title="<?= __('Edit') ?>"
                           class="WweLt-edit-ds">
                            <?= __('Edit') ?>
                        </a> |
                        <a href="javascript:;" data-id="<?= $r['warehouse_id']; ?>" title="<?= __('Delete') ?>"
                           class="WweLt-del-ds">
                            <?= __('Delete') ?>
                        </a>
                    </td>
                </tr>
                <?php
            }
        } ?>
        </tbody>
    </table>
</div>
<!-- Add Popup for new dropship -->
<div id="WweLt-ds-modal" class="add-wh-popup">

    <form method="post" id="WweLt-ds-form" enctype="multipart/form-data" autocomplete="off"
          data-mage-init='{"validation":{}}'>

        <div id="WweLt-ds-modal-msg"></div>
        <input type="hidden" name="location" value="dropship">
        <input type="hidden" name="dropshipId" id="ds-edit-form-id">

        <div class="add-wh-input">
            <div class="wh-input-label">
                <?= __('Nickname') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="input-text" title="<?= __('Nickname') ?>" value="" name="nickname"
                       placeholder="Nickname" id="WweLt-ds-nickname">
            </div>
        </div>

        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= __('Zip') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alphanum" title="<?= __('Zip') ?>" maxlength="6" name="zip"
                       placeholder="30214" id="WweLt-ds-zip">
            </div>
        </div>

        <div class="add-wh-input city-input">
            <div class="wh-input-label add-asterisk">
                <?= __('City') ?>
            </div>
            <div class="wh-input">
                <input class="required" type="text" title="<?= __('City') ?>" name="city" placeholder="Fayetteville"
                       id="ds-city">
            </div>
        </div>

        <div class="add-wh-input city-select" style="display:none;">
            <div class="wh-input-label add-asterisk">
                <?= __('City') ?>
            </div>
            <div class="wh-input">
                <select id="ds-actname" value=""></select>
            </div>
        </div>

        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= __('State') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alpha" title=<?= __('State') ?> maxlength="2"
                       class="alphaonly"
                       name="state" placeholder="GA" id="ds-state">
            </div>
        </div>

        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= __('Country') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alpha" title=<?= __('Country') ?> maxlength="2"
                       name="country"
                       placeholder="US" id="ds-country">
            </div>
        </div>

        <!--In store Pickup Section-->
        <h2 class="wh-heading is-heading-left" id="ds-is-heading-left">
            <?= __('In-store Pick Up') ?>
        </h2>

        <?php if (!$advancedPlan): ?>
            <a class="is-heading-right" href="https://eniture.com/magento2-worldwide-express-ltl-freight">
                <?= __('Advanced Plan Required') ?>
            </a>
        <?php endif; ?>

        <div class="message message-error error ds-instore-miles-postal-err">
            <?= __('You must provide Miles or Postal Code.') ?>
        </div>

        <div id="disableddiv" class="<?= $class ?>">
            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Enable In-Store Pick Up') ?>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= __('Enable In-Store Pick Up') ?>" name="instore_enable"
                           id="ds-enable-instore-pickup" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Offer if address is within (miles):') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Offer if address is within (miles)') ?>" class="digits"
                           maxlength="3"
                           name="is_within_miles" id="ds-within-miles" <?= $disableInput ?> onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Offer if postal code matches:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Offer is postal code matches') ?>"
                           data-role="<?= $advancedPlan ? 'tagsinput' : ''; ?>" name="is_postcode_match"
                           id="ds-postcode-match" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Check Out Description:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Check Out Description') ?>" maxlength="25"
                           name="is_checkout_descp"
                           placeholder="In-store pick up" id="ds-checkout-descp" <?= $disableInput ?>>
                </div>
            </div>
        </div>
        <!--In store Pickup Section End-->

        <!--Local Delivery Section-->

        <div class="row" style="clear: both">
            <h2 class="wh-heading ld-heading-left" id="ds-ld-heading-left">
                <?= __('Local Delivery') ?>
            </h2>
            <?php if (!$advancedPlan): ?>
                <a class="ld-heading-right" href="https://eniture.com/magento2-worldwide-express-ltl-freight/">
                    <?= __('Advanced Plan Required') ?>
                </a>
            <?php endif; ?>
        </div>

        <div class="message message-error error ds-local-miles-postals-err">
            <?= __('You must provide Miles or Postal Code.') ?>
        </div>

        <div id="disableddiv" class="<?= $class ?>">

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Enable Local Delivery') ?>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= __('Enable Local Delivery') ?>" name="ld_enable"
                           id="ds-enable-local-delivery" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Offer if address is within (miles):') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Offer if address is within (miles)') ?>" class="digits"
                           maxlength="3"
                           name="ld_within_miles" id="ds-ld-within-miles" <?= $disableInput ?> onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Offer if postal code matches:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Offer is postal code matches') ?>"
                           data-role="<?= $advancedPlan ? 'tagsinput' : ''; ?>" name="ld_postcode_match"
                           id="ds-ld-postcode-match" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Check Out Description:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Check Out Description') ?>" maxlength="25"
                           name="ld_checkout_descp"
                           placeholder="Local delivery" id="ds-ld-checkout-descp" <?= $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Local Delivery Fee') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= __('Local Delivery Fee') ?>"
                           class="number validate-WweLt-positive-decimal-limit-2" maxlength="5"
                           name="ld_fee" id="ds-ld-fee" <?= $disableInput ?> onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= __('Suppress other rates') ?>
                    <div class="suppressTooltip">[ ? ]
                        <span
                            class="suppressTooltiptext"><?= __("This setting only suppresses rates that would otherwise be returned by the Eniture Technology products.") ?></span>
                    </div>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= __('Suppress other rates') ?>" class="enable-checkbox"
                           name="ld_sup_rates"
                           id="ds-ld-sup-rates" <?= $disableInput ?>>
                </div>
            </div>
        </div>
        <!--Local Delivery Section End-->
    </form>
</div>
